---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord
  namespace: default
spec:
  channel: '#general'
  secretRef:
    name: discord
  type: discord
  username: FluxBot
